import { Bot, GitBranch, BookOpen, Workflow, Eye } from "lucide-react";

export const products = [
  {
    id: "agent-studio",
    slug: "agent-studio",
    title: "Agent Studio",
    tagline: "Build production-ready AI agents without rebuilding your entire stack.",
    shortDescription: "Design, test, and deploy intelligent agents.",
    href: "/platform/agent-studio",
    icon: Bot,
    features: [
      "Create custom AI agents with system prompts",
      "Multi-model selection and tool calling",
      "Conversation and long-term memory",
      "Knowledge base connections",
      "Multi-step task execution and testing",
      "Prompt and agent version management",
      "API access, web embed, and Slack/Teams integration",
      "Structured output and agent run logs",
    ],
    useCase:
      "A support team deploys a production agent that answers common questions, escalates complex tickets, and logs every interaction for review.",
  },
  {
    id: "model-gateway",
    slug: "model-gateway",
    title: "Model Gateway",
    tagline: "One API for every model your business depends on.",
    shortDescription: "Access multiple AI models through one API.",
    href: "/platform/model-gateway",
    icon: GitBranch,
    features: [
      "Unified API for multiple model providers",
      "Automatic routing and failover",
      "Cost control and token usage tracking",
      "Request caching and retry logic",
      "Latency monitoring and model comparison",
      "API key management and rate limiting",
      "Model permissions and call logs",
    ],
    useCase:
      "An engineering team routes requests across OpenAI, Anthropic, and a private model — switching providers without changing application code.",
    providers: ["OpenAI", "Anthropic", "Google Gemini", "Mistral", "DeepSeek", "Groq", "Azure OpenAI", "AWS Bedrock", "Private Models", "Local Models"],
  },
  {
    id: "knowledge-layer",
    slug: "knowledge-layer",
    title: "Knowledge Layer",
    tagline: "Turn scattered company knowledge into reliable AI answers.",
    shortDescription: "Ground AI responses in your company data.",
    href: "/platform/knowledge-layer",
    icon: BookOpen,
    features: [
      "Upload PDF, Word, Excel, and Markdown",
      "Website crawling and knowledge base sync",
      "Document chunking, embedding, and vector search",
      "Hybrid search and RAG with source citations",
      "Document permissions and version management",
      "Multi-language queries and quality assessment",
      "Data connectors and enterprise permissions",
    ],
    useCase:
      "An operations team connects Notion, Confluence, and internal docs so employees get accurate answers with cited sources.",
    sources: ["Google Drive", "Notion", "Confluence", "Slack", "Dropbox", "CRM", "Databases", "APIs", "Cloud Storage"],
  },
  {
    id: "workflows",
    slug: "workflows",
    title: "Workflow Automation",
    tagline: "Automate complex work with AI-powered workflows.",
    shortDescription: "Turn repetitive processes into intelligent workflows.",
    href: "/platform/workflows",
    icon: Workflow,
    features: [
      "Visual workflow editor with conditions",
      "Agent, API, database, and document nodes",
      "Email, webhook, and scheduled triggers",
      "Human approval steps and error retry",
      "Workflow templates and version management",
      "Run logs and monitoring",
    ],
    useCase:
      "A sales team automates lead research, CRM updates, and personalized outreach — reducing manual data entry by hours each week.",
    scenarios: [
      "Auto-read customer emails and draft replies",
      "Support ticket classification and escalation",
      "Contract key information extraction",
      "Meeting summaries and task creation",
      "CRM updates and business report generation",
    ],
  },
  {
    id: "observability",
    slug: "observability",
    title: "Observability & Governance",
    tagline: "Monitor every AI interaction with clarity and control.",
    shortDescription: "Monitor quality, latency, usage, and cost.",
    href: "/platform/observability",
    icon: Eye,
    features: [
      "AI and agent call logs with prompt versions",
      "Model cost and token analysis",
      "Request latency, errors, and success rates",
      "User feedback and model quality evaluation",
      "Content safety and sensitive data filtering",
      "PII detection, RBAC, and audit logs",
      "Enterprise SSO and data retention policies",
    ],
    useCase:
      "A platform team tracks model costs across teams, identifies underperforming agents, and enforces content safety policies.",
  },
];
