export const solutions = [
  {
    slug: "customer-support",
    title: "AI Customer Support",
    shortTitle: "Customer Support",
    tagline: "Resolve common questions instantly and route complex cases to the right person.",
    painPoints: [
      "Support teams overwhelmed by repetitive questions",
      "Inconsistent answers across channels",
      "Long resolution times for complex issues",
      "No visibility into AI-assisted interactions",
    ],
    howItHelps: [
      "Deploy support agents grounded in your knowledge base",
      "Automatically classify and route tickets",
      "Escalate complex cases to human agents with context",
      "Monitor quality, latency, and customer satisfaction",
    ],
    features: ["Agent Studio", "Knowledge Layer", "Workflow Automation", "Observability"],
    integrations: ["Slack", "Microsoft Teams", "Zendesk", "Intercom", "Webhooks", "REST API"],
    results: [
      "Faster first-response times for common questions",
      "Consistent answers based on approved documentation",
      "Reduced manual triage for support teams",
      "Full audit trail of AI-assisted interactions",
    ],
  },
  {
    slug: "knowledge-assistant",
    title: "Internal Knowledge Assistant",
    shortTitle: "Knowledge Assistant",
    tagline: "Give employees reliable answers based on approved company information.",
    painPoints: [
      "Critical knowledge scattered across tools",
      "Employees waste time searching for answers",
      "Outdated documentation leads to errors",
      "No single source of truth for internal queries",
    ],
    howItHelps: [
      "Connect documents, wikis, and databases",
      "Provide cited answers from approved sources",
      "Sync and update knowledge automatically",
      "Control access with enterprise permissions",
    ],
    features: ["Knowledge Layer", "Agent Studio", "Model Gateway", "Observability"],
    integrations: ["Notion", "Confluence", "Google Drive", "Slack", "SharePoint", "Databases"],
    results: [
      "Employees find answers in seconds, not hours",
      "Answers include source citations for verification",
      "Knowledge stays current with automatic sync",
      "Role-based access protects sensitive information",
    ],
  },
  {
    slug: "document-intelligence",
    title: "Document Intelligence",
    shortTitle: "Document Intelligence",
    tagline: "Extract, classify, compare, and summarize documents at scale.",
    painPoints: [
      "Manual document review is slow and error-prone",
      "Key information buried in lengthy contracts",
      "Inconsistent classification across teams",
      "No scalable way to process document volumes",
    ],
    howItHelps: [
      "Extract structured data from PDFs and contracts",
      "Classify and route documents automatically",
      "Compare versions and highlight differences",
      "Generate summaries and audit reports",
    ],
    features: ["Knowledge Layer", "Workflow Automation", "Agent Studio", "Observability"],
    integrations: ["Google Drive", "Dropbox", "S3", "SharePoint", "Email", "Webhooks"],
    results: [
      "Faster contract and document review cycles",
      "Structured extraction of key fields and clauses",
      "Automated classification and routing",
      "Searchable document archives with metadata",
    ],
  },
  {
    slug: "sales-automation",
    title: "Sales Operations",
    shortTitle: "Sales Automation",
    tagline: "Research leads, update CRM records, and prepare personalized outreach.",
    painPoints: [
      "Reps spend hours on manual research and data entry",
      "CRM records are incomplete or outdated",
      "Personalized outreach is time-consuming",
      "No unified view of lead intelligence",
    ],
    howItHelps: [
      "Automate lead research and enrichment",
      "Update CRM records from conversations and emails",
      "Generate personalized outreach drafts",
      "Track agent performance and conversion metrics",
    ],
    features: ["Workflow Automation", "Agent Studio", "Knowledge Layer", "Model Gateway"],
    integrations: ["Salesforce", "HubSpot", "Email", "LinkedIn", "Webhooks", "REST API"],
    results: [
      "More time for high-value selling activities",
      "Cleaner, more complete CRM data",
      "Personalized outreach at scale",
      "Visibility into pipeline automation performance",
    ],
  },
  {
    slug: "data-analysis",
    title: "Data Analysis",
    shortTitle: "Data Analysis",
    tagline: "Turn natural-language questions into structured business insights.",
    painPoints: [
      "Business users depend on analysts for simple queries",
      "Data is spread across multiple systems",
      "Ad-hoc analysis is slow and inconsistent",
      "No self-service access to reliable insights",
    ],
    howItHelps: [
      "Connect databases and data warehouses",
      "Answer questions in natural language",
      "Generate structured reports and visualizations",
      "Enforce permissions on sensitive data",
    ],
    features: ["Agent Studio", "Knowledge Layer", "Workflow Automation", "Observability"],
    integrations: ["PostgreSQL", "MySQL", "Snowflake", "BigQuery", "REST API", "CSV"],
    results: [
      "Self-service insights for business teams",
      "Consistent, auditable query results",
      "Automated report generation on schedule",
      "Controlled access to sensitive datasets",
    ],
  },
  {
    slug: "developer-platform",
    title: "Developer AI Platform",
    shortTitle: "Developer Tools",
    tagline: "Add model routing, RAG, agents, and monitoring without building infrastructure from scratch.",
    painPoints: [
      "Building AI infrastructure from scratch is expensive",
      "Model-specific integrations create vendor lock-in",
      "No unified observability across AI features",
      "Production reliability requires significant engineering",
    ],
    howItHelps: [
      "Use unified APIs for agents, RAG, and workflows",
      "Route across multiple models with one integration",
      "Monitor costs, latency, and errors in production",
      "Scale from prototype to production quickly",
    ],
    features: ["Model Gateway", "Agent Studio", "Knowledge Layer", "Observability"],
    integrations: ["REST API", "JavaScript SDK", "Python SDK", "Webhooks", "GitHub", "CI/CD"],
    results: [
      "Ship AI features in days, not months",
      "Model-agnostic architecture from day one",
      "Production-grade monitoring and governance",
      "Developer-friendly APIs and documentation",
    ],
  },
];

export function getSolution(slug: string) {
  return solutions.find((s) => s.slug === slug);
}
